# ==============================================================================
# V-RATIO FITTING ENGINE (fit.R)
# DO NOT EDIT THIS FILE! Change your settings in 'run_pipeline.R'.
# ==============================================================================

Sys.setenv(LC_ALL = "C")
Sys.setenv(LANG = "C")
suppressPackageStartupMessages({
  library(Rcpp); library(DEoptim); library(dplyr); library(RcppZiggurat); library(data.table); library(here)
  source(here("helper_functions.R"))
  sourceCpp(here("models.cpp"))
})

# ==============================================================================
# 1. READ ARGUMENTS
# ==============================================================================
args <- commandArgs(trailingOnly = TRUE)
if (length(args) < 2) stop("Engine requires 2 arguments: Subject_Index and Config_Path")

subj_arg    <- args[1]
CONFIG_PATH <- args[2]

# ==============================================================================
# 2. LOAD SETTINGS FROM CONTROLLER
# ==============================================================================
load(CONFIG_PATH)

# Determine Subject Index
if (subj_arg == "GROUP") {
  SUBJECT_IDX <- NULL
} else {
  SUBJECT_IDX <- as.numeric(subj_arg)
}

# ==============================================================================
# 3. PIPELINE INTERNAL SETTINGS
# ==============================================================================
COST_METHOD   <- "gsquare"
sim_constants <- list(ntrials = 5000, s = 1, dt = .001)
TRACE         <- ITER_MAX / 10 
POP_SCALE     <- 10
N_PRED        <- 10000

# Auto-detect experimental conditions to split G-Square likelihood blocks safely
cond_col_names <- if(length(VARYING_PARAMS) > 0) {
  unique(unlist(lapply(VARYING_PARAMS, function(x) if(inherits(x, "formula")) all.vars(x) else x)))
} else { NULL }

# Define how the cost function should be built
FIT_TARGETS <- list(
  # Eq 4: Primary RT shape, split by Accuracy
  list(rt_col = "rt", split_cols = c("acc", cond_col_names), weight = 1),
  
  # Eq 5: Confidence RT shape, split by Accuracy
  list(rt_col = "rtconf", split_cols = c("acc", cond_col_names), weight = 1),
  
  # Eq 6: Pure confidence proportions
  list(rt_col = "cj", split_cols = c("acc", "cj", cond_col_names), weight = 1) 
)

print(paste("Active Configuration -> Subject:", ifelse(is.null(SUBJECT_IDX), "Group", SUBJECT_IDX)))

# ==============================================================================
# 4. LOADING AND FILTERING DATA
# ==============================================================================
DATA_FILE <- here("data", DATA_NAME) 
if (!file.exists(DATA_FILE)) stop(paste("File not found:", DATA_FILE))

if (grepl("\\.rds$", DATA_FILE, ignore.case = TRUE)) {
  raw_data <- readRDS(DATA_FILE)
} else {
  raw_data <- as.data.frame(data.table::fread(DATA_FILE))
}
OUTPUT_DIR <- here("results", OUTPUT_FOLDER)

# Check for required columns
required_cols <- c("rt", "acc", "rtconf", "cj", SUBJECT_COL)
missing_cols <- setdiff(required_cols, names(raw_data))
if (length(missing_cols) > 0) {
  stop(paste("\n[DATA ERROR] Your data is missing the following required columns:", 
             paste(missing_cols, collapse = ", "), 
             "\nPlease rename your columns to match exactly: rt, acc, rtconf, cj"))
}

# Ensure numeric RTs
raw_data$rt <- as.numeric(as.character(raw_data$rt))
raw_data$rtconf <- as.numeric(as.character(raw_data$rtconf))

# Handle subject filtering
if (!is.null(SUBJECT_IDX)) {
  all_subjects <- sort(unique(raw_data[[SUBJECT_COL]]))
  target_sub_id <- all_subjects[SUBJECT_IDX]
  SUBJECT_ID_VAL <- target_sub_id
  observations <- raw_data[raw_data[[SUBJECT_COL]] == target_sub_id, ]
  print(paste("Filtering Subject Index:", SUBJECT_IDX, "-> ID:", target_sub_id))
} else {
  observations <- raw_data
  SUBJECT_ID_VAL <- "GROUP"
  print("Fitting Group/All Data.")
}
if (nrow(observations) == 0) stop("No data found for the selected subject...")

# ==============================================================================
# 5. CONFIGURE PARAMETER SPACE
# ==============================================================================
config <- get_param_config(MODEL_NAME, VARYING_PARAMS, observations)
config <- fix_parameters(config, FIXED_PARAMS)
fit_constants <- c(config$fixed, sim_constants)

# ==============================================================================
# 6. STANDARDIZATION OF THE FACTORS
# ==============================================================================
# Safety checks for user data input
if (MODEL_NAME == "FCB_cj2" && !all(raw_data$cj %in% c(0, 1), na.rm = TRUE)) {
  stop("\n[DATA ERROR] You selected FCB_cj2, but your 'cj' column contains invalid values. Please recode your binary confidence to 0 (Low) and 1 (High).")
}
if (MODEL_NAME == "FCB_cj6" && !all(raw_data$cj %in% 1:6, na.rm = TRUE)) {
  stop("\n[DATA ERROR] You selected FCB_cj6, but your 'cj' column contains values outside the 1-6 range.")
}

observations$acc <- factor(observations$acc, levels = c(0, 1))

if("cj" %in% names(observations)) {
  cj_levels <- if(MODEL_NAME == "FCB_cj6") 1:6 else 0:1
  observations$cj <- factor(observations$cj, levels = cj_levels)
}

# Ensure condition columns are factors
if (!is.null(cond_col_names)) {
  for (col_name in cond_col_names) {
    if (col_name %in% names(raw_data)) {
      master_lvls <- sort(unique(raw_data[[col_name]]))
      observations[[col_name]] <- factor(observations[[col_name]], levels = master_lvls)
      cat(sprintf("Factorized column: %s | Intercept baseline: %s\n", col_name, master_lvls[1]))
    }
  }
}

print(paste("Observations ready:", nrow(observations), "trials."))

# ==============================================================================
# 7. RUN OPTIMIZATION
# ==============================================================================

ctrl <- DEoptim.control(
  itermax = ITER_MAX, 
  trace   = TRACE,
  NP      = POP_SCALE * length(config$lower),
  parallelType = USE_CORES, 
  packages     = c("Rcpp", "RcppZiggurat", "dplyr"),
  parVar       = c("FIT_TARGETS", "VARYING_PARAMS", "MODEL_NAME") 
)

print(paste("Starting DEoptim on", length(config$lower), "parameters..."))
start_time <- Sys.time()

# --- VALIDATION ---
cat("\nValidating configuration...")
is_regression <- any(sapply(VARYING_PARAMS, function(x) inherits(x, "formula")))
all_design_vars <- unique(unlist(lapply(VARYING_PARAMS, all.vars)))

# Print mapping overview
cat("\nParameter mapping overview:")
for (p in names(get_model_params(MODEL_NAME))) {
  if (p %in% names(VARYING_PARAMS)) {
    cat(sprintf("\n  [VARYING] %-10s -> Formula: %s", p, deparse(VARYING_PARAMS[[p]])))
  } else if (p %in% names(fit_constants)) {
    cat(sprintf("\n  [FIXED]   %-10s -> Value: %s", p, fit_constants[[p]]))
  } else {
    cat(sprintf("\n  [SHARED]  %-10s -> Estimated globally", p))
  }
}
cat("\n\nStarting optimization...\n")

cat("\n==================================================\n")
cat("FREE PARAMETERS (Optimizing):\n")
cat(sprintf("  %-4s %-25s %-20s\n", "Idx", "Parameter Name", "Bounds [Min, Max]"))
cat("  --------------------------------------------------\n")
for (i in seq_along(config$lower)) {
  cat(sprintf("  [%02d] %-25s [%.4f, %.4f]\n", i, config$names[i], config$lower[i], config$upper[i]))
}
cat("==================================================\n")

result <- DEoptim(
  fn = objective_function, 
  lower = config$lower, 
  upper = config$upper,
  observations   = observations,
  param_names    = config$names,
  constants      = fit_constants,
  model_fun      = MODEL_NAME, 
  targets        = FIT_TARGETS, 
  cost_method    = COST_METHOD,  
  varying_params = VARYING_PARAMS,
  control        = ctrl
)

duration <- Sys.time() - start_time
print(paste("Optimization finished in:", round(duration, 2), units(duration)))

# ==============================================================================
# 8. GENERATE HIGH RESOLUTION PREDICTIONS
# ==============================================================================

print(paste("Generating best-fit predictions with", N_PRED, "trials..."))

best_params <- result$optim$bestmem
best_betas  <- NULL

is_regression <- any(sapply(VARYING_PARAMS, function(x) inherits(x, "formula")))

if (is_regression) {
  cat("Translating Regression Betas to Marginal Cell Means...\n")
  best_betas <- best_params 
  reconstructed_params <- c()
  
  all_cond_cols <- unique(unlist(lapply(VARYING_PARAMS, all.vars)))
  cond_grid <- unique(observations[, all_cond_cols, drop = FALSE])
  p_base_names <- names(get_model_params(MODEL_NAME))
  
  for (i in 1:nrow(cond_grid)) {
    current_cell <- cond_grid[i, , drop = FALSE]
    p_lvl <- pluck_params(best_betas, fit_constants, current_cell, VARYING_PARAMS, MODEL_NAME)
    
    for (p in p_base_names) {
      if (p %in% names(VARYING_PARAMS)) {
        p_formula <- VARYING_PARAMS[[p]]
        p_vars <- all.vars(p_formula)
        if (length(p_vars) > 0) {
          p_lvl_val <- paste(unlist(current_cell[, p_vars, drop = FALSE]), collapse = ".")
          reconstructed_params[paste0(p, ":", p_lvl_val)] <- p_lvl[[p]]
        } else {
          reconstructed_params[p] <- p_lvl[[p]]
        }
      } else if (!p %in% names(fit_constants)) {
        reconstructed_params[p] <- p_lvl[[p]]
      }
    }
  }
  best_params <- reconstructed_params[!duplicated(names(reconstructed_params))]
}

# Override trial count for high-res predictions
pred_constants <- fit_constants
pred_constants$ntrials <- N_PRED

sim_varying_params <- list()
for (p in names(VARYING_PARAMS)) sim_varying_params[[p]] <- all.vars(VARYING_PARAMS[[p]])

final_predictions <- objective_function(
  params         = best_params,
  observations   = observations,
  param_names    = names(best_params),
  constants      = pred_constants,
  model_fun      = MODEL_NAME,
  targets        = FIT_TARGETS, 
  varying_params = sim_varying_params,
  returnFit      = 0 
)

# Align Factor Levels for Plotting
for (col in names(observations)) {
  if (col %in% names(final_predictions) && is.factor(observations[[col]])) {
    final_predictions[[col]] <- factor(final_predictions[[col]], levels = levels(observations[[col]]))
  }
}

final_proportions <- objective_function(
  params         = best_params,
  observations   = observations,
  param_names    = names(best_params),
  constants      = pred_constants,
  model_fun      = MODEL_NAME,
  targets        = FIT_TARGETS, 
  varying_params = sim_varying_params, 
  returnFit      = 2
)

n_bins_total <- attr(result$optim$bestval, "n_bins")
if (is.null(n_bins_total)) { 
  n_bins_total <- sum(unlist(lapply(final_proportions, function(target_list) {
    sum(sapply(target_list, function(level) length(level$obs)))
  })))
}

# ==============================================================================
# 9. REPORTING & SAVING
# ==============================================================================

n_free_params  <- length(config$lower) 
fit_metrics <- list(
  n_observations = nrow(observations),
  n_free_params  = n_free_params,
  n_bins         = n_bins_total,
  best_cost      = result$optim$bestval,
  bic = result$optim$bestval + n_free_params * log(nrow(observations)),
  aic = result$optim$bestval + 2 * n_free_params
)

fit_output <- list(
  best_params  = best_params,
  best_betas   = best_betas,  
  fit_metrics  = fit_metrics,
  optim_full   = result,
  param_info   = config,
  constants    = fit_constants,
  targets      = FIT_TARGETS,
  cost_method  = COST_METHOD,
  observations = observations,
  predictions  = final_predictions,
  final_proportions = final_proportions,
  info = list(
    model          = MODEL_NAME,
    timestamp      = Sys.time(),
    subject        = SUBJECT_ID_VAL,
    varying_params = VARYING_PARAMS
  )
)

if (!dir.exists(OUTPUT_DIR)) dir.create(OUTPUT_DIR, recursive = TRUE)
file_base <- paste0(MODEL_NAME, "_FIT_sub-", SUBJECT_ID_VAL, "_", format(Sys.time(), "%Y%m%d_%H%M%S"))
saveRDS(fit_output, file.path(OUTPUT_DIR, paste0(file_base, ".rds")))
print(paste("Best Cost:", round(fit_metrics$best_cost, 4)))

# ==============================================================================
# 10. VISUALIZATION
# ==============================================================================
cat("\nGenerating diagnostic reports...\n")

plot_dist(obs = fit_output$observations, pred = fit_output$predictions, 
          val_col = "rt", split_by_acc = TRUE, main_title = "Decision RT")

plot_dist(obs = fit_output$observations, pred = fit_output$predictions, 
          val_col = "rtconf", split_by_acc = TRUE, main_title = "Confidence RT")

p_cj <- plot_cj_distribution(fit_output$observations, fit_output$predictions)
if (!is.null(p_cj)) print(p_cj)

pdf_path <- file.path(OUTPUT_DIR, paste0(file_base, ".pdf"))
pdf(file = pdf_path, width = 10, height = 6)

plot_dist(obs = fit_output$observations, pred = fit_output$predictions, 
          val_col = "rt", split_by_acc = TRUE, main_title = "Decision RT")

plot_dist(obs = fit_output$observations, pred = fit_output$predictions, 
          val_col = "rtconf", split_by_acc = TRUE, main_title = "Confidence RT")

if (!is.null(p_cj)) print(p_cj)

dev.off() 
cat(sprintf("\nPDF Report saved to: %s\n", pdf_path))